reporter: xcode

# You can read more about rules
# https://realm.github.io/SwiftLint/rule-directory.html

# Disabled rules from runnig
disabled_rules: 
  - trailing_whitespace
  - cyclomatic_complexity
  - valid_ibinspectable

# Opt in rules for runnig
opt_in_rules: 
  - closure_end_indentation
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - file_header
  - file_name_no_space
  - first_where
  - force_unwrapping
  - implicit_return
  - implicitly_unwrapped_optional
  - indentation_width
  - joined_default_parameter
  - last_where
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_function_chains
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_zero_over_explicit_init
  - prohibited_super_call
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - yoda_condition

# Exclude non-manageable folders
excluded:
  - ".swiftlint.yml"
  - Pods
  - Resources/Resources

file_header:
  required_pattern: \/\/ Copyright © \d{4} .*?\. All rights reserved\.

# Configured length rules
identifier_name:
  min_length: 1

line_length:
  warning: 200
  ignores_comments: true

type_body_length:
  warning: 400
  error: 500

function_body_length:
  warning: 80
  error: 100

file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

type_name:
  min_length: 2
  max_length:
    warning: 50
    error: 60

# Configured rules
nesting:
  type_level: 2

empty_count:
  severity: warning
  only_after_dot: true
