reporter: xcode

warning_threshold: 15

opt_in_rules:
  - force_unwrapping
  - force_try
  - force_cast
  - vertical_whitespace
  - empty_count
  - closure_end_indentation
  - closure_spacing
  - explicit_init
  - first_where
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - weak_delegate

# Disables rules
disabled_rules:
  - file_length
  - trailing_whitespace
  - nesting

# Custom configurations
line_length:
  warning: 200
  ignores_comments: true

force_unwrapping: warning
force_try: warning
force_cast: warning

weak_delegate: error

function_parameter_count:
  warning: 10
  error: 15

function_body_length:
  - 80
  - 100

type_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
    error: 60

type_body_length:
  warning: 400
  error: 500

identifier_name:
  min_length:
    warning: 1
  max_length:
    warning: 40
    error: 60

shorthand_operator: warning

# Custom rules
custom_rules:
  comments_space:
    name: "Space After Comment"
    regex: '(^ *//\w+)'
    message: "There should be a space after //"
    severity: warning

  empty_closure_params:
    included: ".*.swift"
    name: "Empty closure params"
    regex: '\{ (\(\) -> Void in)$'
    message: "`() -> Void in` should be avoided"
    severity: warning

  final_class:
    included: ".*.swift"
    name: "Final class requrement"
    regex: '^class'
    message: "All classes must be final or nonfinal"
    saverity: error