name: Prepare to deploy

on: 
  pull_request:
    branches:
      - master
    paths:
      - 'AirKit/Source/**'
      - 'AirKitTests/Source/**'
      - 'AirKitTests/Resource/**'

jobs:
  testing:
    runs-on: macOS-latest
    timeout-minutes: 10
    steps:
    
    - name: Checkout pull request branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Select lates available version of Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
      
    - name: Build project for iOS
      run: |
        xcodebuild test -project AirKit.xcodeproj -scheme AirKit -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=latest' | xcpretty && exit ${PIPESTATUS[0]}

  checking_linter:
    runs-on: macOS-latest
    timeout-minutes: 5
    steps:

    - name: Checkout pull request branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Check Pod linter
      run: |
        pod lib lint AirKit.podspec
    