name: Tag has been created

on:
  push:
    tags:
      - '*.*.*' # Push events to matching `*.*.*`, i.e. 1.0.0, v20.15.10

jobs:
  create_release_draft:
    name: Create release draft
    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout tag branch
      uses: actions/checkout@v2

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

    - name: Create release draft
      id: create_release_draft
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: v ${{ github.event.base.ref }}
        draft: true
        prerelease: true